version: '3.7'

services:
    app:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    app-data: